<a href="https://colab.research.google.com/github/pooja140703/GST_Hackathon/blob/main/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Step 1: Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Step 2: Load your dataset
# Assuming Dtrain and Dtest are already loaded as numpy arrays or pandas DataFrames
import pandas as pd

# Load the test input features
X_test = pd.read_csv('/content/X_Train_Data_Input3.csv')

# Load the test target data
Y_test = pd.read_csv('/content/Y_Train_Data_Target3.csv')

# Inspect the first few rows of the data
print(X_test.head())
print(Y_test.head())





                                 ID  Column0  Column1  Column2   Column3  \
0  ad1a67e4cbddc767a3456b0d94299b9e      2.0     2495   3726.0  0.678139   
1  7246d2f76ac0c217ec25e72ea5f014cb      0.0     2495   3454.0  0.452580   
2  22ba388e7dd14c13342c49e75fc29dda      2.0     2495   4543.0 -1.577453   
3  59f9b981472d97342587fb3e6392aeb1      0.0      211     59.0 -0.000210   
4  f6317cf7ecf126859804eddff279aead      0.0      718    950.0 -2.028572   

    Column4   Column6   Column7   Column8  Column10  Column11  Column12  \
0  0.701403  0.434190 -0.015603  0.606265       0.0       0.0       0.0   
1  0.701403  1.554998 -0.015574  0.329946       0.0       0.0       0.0   
2 -1.429540 -0.407939 -0.015607 -0.774979       1.0       1.0       1.0   
3 -0.000855 -0.407939 -0.015607 -0.774979       0.0       0.0       0.0   
4 -1.855728 -0.407939 -0.015607 -0.774979       0.0       0.0       0.0   

   Column13  Column15  Column16  Column17  Column18  Column19  Column20  \
0       0.0   0.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
DATA_PATH = "/content/Y_Train_Data_Target2.csv"
data = pd.read_csv(DATA_PATH)
data.head()

ID  target
0  ad1a67e4cbddc767a3456b0d94299b9e     0.0
1  7246d2f76ac0c217ec25e72ea5f014cb     0.0
2  22ba388e7dd14c13342c49e75fc29dda     0.0
3  59f9b981472d97342587fb3e6392aeb1     1.0
4  f6317cf7ecf126859804eddff279aead     0.0

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

In [ ]:
df = pd.read_csv('/content/X_Train_Data_Input3.csv')  # Replace with your file path

# Check if the dataset is loaded
print(df.head())
# DATA_PATH1 = "/content/X_Train_Data_Input2.csv"
# data = pd.read_csv(DATA_PATH1)
# data.head()

                                 ID  Column0  Column1  Column2   Column3  \
0  ad1a67e4cbddc767a3456b0d94299b9e      2.0     2495   3726.0  0.678139   
1  7246d2f76ac0c217ec25e72ea5f014cb      0.0     2495   3454.0  0.452580   
2  22ba388e7dd14c13342c49e75fc29dda      2.0     2495   4543.0 -1.577453   
3  59f9b981472d97342587fb3e6392aeb1      0.0      211     59.0 -0.000210   
4  f6317cf7ecf126859804eddff279aead      0.0      718    950.0 -2.028572   

    Column4   Column6   Column7   Column8  Column10  Column11  Column12  \
0  0.701403  0.434190 -0.015603  0.606265         0         0         0   
1  0.701403  1.554998 -0.015574  0.329946         0         0         0   
2 -1.429540 -0.407939 -0.015607 -0.774979         1         1         1   
3 -0.000855 -0.407939 -0.015607 -0.774979         0         0         0   
4 -1.855728 -0.407939 -0.015607 -0.774979         0         0         0   

   Column13  Column15  Column16  Column17  Column18  Column19  Column20  \
0         0   0.0

In [ ]:
DATA_PATH = "/content/Y_Train_Data_Target2.csv"
data = pd.read_csv(DATA_PATH)
data

ID  target
0     ad1a67e4cbddc767a3456b0d94299b9e     0.0
1     7246d2f76ac0c217ec25e72ea5f014cb     0.0
2     22ba388e7dd14c13342c49e75fc29dda     0.0
3     59f9b981472d97342587fb3e6392aeb1     1.0
4     f6317cf7ecf126859804eddff279aead     0.0
...                                ...     ...
5404  c049cb3c4683b34c859e5deb1434647e     0.0
5405  06db117e4198395f369376966aa75d98     0.0
5406  64ae901c7a7cfefe2d07639ca8d02ed9     0.0
5407  92273136701a970657c2cd5b9f6130d4     0.0
5408  b673ff1be8ffb406c6ca8a2bdcc45772     NaN

[5409 rows x 2 columns]

In [ ]:
DATA_PATH = "/content/X_Train_Data_Input3.csv"
data = pd.read_csv(DATA_PATH)
data

ID  Column0  Column1  Column2   Column3  \
0       ad1a67e4cbddc767a3456b0d94299b9e      2.0     2495   3726.0  0.678139   
1       7246d2f76ac0c217ec25e72ea5f014cb      0.0     2495   3454.0  0.452580   
2       22ba388e7dd14c13342c49e75fc29dda      2.0     2495   4543.0 -1.577453   
3       59f9b981472d97342587fb3e6392aeb1      0.0      211     59.0 -0.000210   
4       f6317cf7ecf126859804eddff279aead      0.0      718    950.0 -2.028572   
...                                  ...      ...      ...      ...       ...   
785128  01b7d7be203dbf2a3d75c9770d68dfb6      0.0      304   1126.0  0.678139   
785129  c7993f2c4c15f46f366f6daaa747197d      0.0     2495   2265.0  0.678139   
785130  a34b544f113a6d3b4eb353909a378afb      0.0     2495   3760.0  0.678139   
785131  fe5b1826c9e7c1864886b233402df330      0.0     2480   4493.0  0.001462   
785132  c3862b6625043b647d275e9825a7d6ea      0.0     2495   4202.0  0.678139   

         Column4   Column6   Column7   Column8  Column10  Column11  Column12  \
0       0.701403  0.434190 -0.015603  0.606265         0         0         0   
1       0.701403  1.554998 -0.015574  0.329946         0         0         0   
2      -1.429540 -0.407939 -0.015607 -0.774979         1         1         1   
3      -0.000855 -0.407939 -0.015607 -0.774979         0         0         0   
4      -1.855728 -0.407939 -0.015607 -0.774979         0         0         0   
...          ...       ...       ...       ...       ...       ...       ...   
785128  0.701403 -0.407939 -0.015607 -0.774979         0         0         0   
785129  0.701403 -0.407939 -0.015607  0.509591         1         1         1   
785130  0.701403 -0.407939 -0.015607  0.218972         0         0         1   
785131  0.062121 -0.407939 -0.015607  0.400071         1         1         1   
785132  0.701403  3.440511 -0.015603  0.471097         0         0         0   

        Column13  Column15  Column16  Column17  Column18  Column19  Column20  \
0              0   0.00339       0.0         0       0.0         0         0   
1              0   0.00339       0.0         0       0.0         0         0   
2              1   0.00339       0.0         0       0.0         0         0   
3              0   0.00339       0.0         0       1.0         0         0   
4              0   0.00339       0.0         0       0.0         0         0   
...          ...       ...       ...       ...       ...       ...       ...   
785128         0   0.00339       0.0         0       1.0         0         0   
785129         1   0.00339       0.0         0       0.0         0         0   
785130         1   0.00339       0.0         0       0.0         0         0   
785131         1   0.00339       0.0         0       0.0         0         0   
785132         0   0.00339       0.0         0       0.0         0         0   

        Column21  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
785128         0  
785129         0  
785130         0  
785131         0  
785132         0  

[785133 rows x 20 columns]

In [ ]:
X_train_input = data.drop('ID', axis=1).values  # Replace 'target' with actual target column name
Y_train_target = t['target'].values
# Y_train_target = df.reshape(-1, 1)

In [ ]:
X_train_input


array([[2.000e+00, 2.495e+03, 3.726e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.495e+03, 3.454e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.000e+00, 2.495e+03, 4.543e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [0.000e+00, 2.427e+03, 1.154e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.495e+03, 2.328e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.484e+03, 5.637e+03, ...,       nan,       nan,
              nan]])

In [ ]:
DATA_PATH1 = "/content/Y_Train_Data_Target3.csv"
t = pd.read_csv(DATA_PATH1)
t

ID  target
0       ad1a67e4cbddc767a3456b0d94299b9e       0
1       7246d2f76ac0c217ec25e72ea5f014cb       0
2       22ba388e7dd14c13342c49e75fc29dda       0
3       59f9b981472d97342587fb3e6392aeb1       1
4       f6317cf7ecf126859804eddff279aead       0
...                                  ...     ...
785128  01b7d7be203dbf2a3d75c9770d68dfb6       0
785129  c7993f2c4c15f46f366f6daaa747197d       0
785130  a34b544f113a6d3b4eb353909a378afb       0
785131  fe5b1826c9e7c1864886b233402df330       0
785132  c3862b6625043b647d275e9825a7d6ea       0

[785133 rows x 2 columns]

In [ ]:
if len(Y_train_target.shape) == 1:
    Y_train_target = Y_train_target.reshape(-1, 1)

In [ ]:
print("Shape of X_train_input:", X_train_input.shape)
print("Shape of Y_train_target:", Y_train_target.shape)

Shape of X_train_input: (172543, 19)
Shape of Y_train_target: (785133, 1)


In [ ]:
Y_train_target

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train_input, Y_train_target, test_size=0.2, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [172543, 785133]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train_input_cleaned, Y_train_target_cleaned, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of Y_train:", Y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of Y_test:", Y_test.shape)

Shape of X_train: (135151, 19)
Shape of Y_train: (135151,)
Shape of X_test: (33788, 19)
Shape of Y_test: (33788,)


In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train_scaled, Y_train)

LogisticRegression(max_iter=1000)

In [ ]:
Y_pred_test = model.predict(X_test_scaled)

In [ ]:
accuracy = accuracy_score(Y_test, Y_pred_test)
print(f"Accuracy: {accuracy * 100:.2f}%")



# Confusion matrix
conf_matrix = confusion_matrix(Y_test, Y_pred_test)
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 96.89%
Confusion Matrix:
[[30131   683]
 [  368  2606]]


In [ ]:
# Combine X_train_input and Y_train_target into a single DataFrame to check for missing values
df_combined = pd.concat([pd.DataFrame(X_train_input), pd.DataFrame(Y_train_target)], axis=1)

# Drop rows where either X or Y has missing values
df_combined_cleaned = df_combined.dropna()

# Extract the cleaned feature matrix and target variable
X_train_input_cleaned = df_combined_cleaned.iloc[:, :-1].values  # Features
Y_train_target_cleaned = df_combined_cleaned.iloc[:, -1].values  # Target
X_train_input_cleaned


array([[2.000e+00, 2.495e+03, 3.726e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.495e+03, 3.454e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.000e+00, 2.495e+03, 4.543e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [1.000e+00, 1.503e+03, 8.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.427e+03, 1.154e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 2.495e+03, 2.328e+03, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [ ]:
Y_train_target_cleaned

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Import necessary libraries
from sklearn.svm import SVC  # For Support Vector Classification
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  # For evaluation


In [ ]:
# Create the SVM model
svm_model = SVC(kernel='linear', random_state=42)  # You can try other kernels like 'rbf', 'poly', or 'sigmoid'

# Train the SVM model using the training data
svm_model.fit(X_train, Y_train)


NameError: name 'SVC' is not defined

In [ ]:
print(data.tail())

                                      ID  Column0  Column1  Column2   Column3  \
785128  01b7d7be203dbf2a3d75c9770d68dfb6      0.0      304   1126.0  0.678139   
785129  c7993f2c4c15f46f366f6daaa747197d      0.0     2495   2265.0  0.678139   
785130  a34b544f113a6d3b4eb353909a378afb      0.0     2495   3760.0  0.678139   
785131  fe5b1826c9e7c1864886b233402df330      0.0     2480   4493.0  0.001462   
785132  c3862b6625043b647d275e9825a7d6ea      0.0     2495   4202.0  0.678139   

         Column4   Column6   Column7   Column8  Column10  Column11  Column12  \
785128  0.701403 -0.407939 -0.015607 -0.774979         0         0         0   
785129  0.701403 -0.407939 -0.015607  0.509591         1         1         1   
785130  0.701403 -0.407939 -0.015607  0.218972         0         0         1   
785131  0.062121 -0.407939 -0.015607  0.400071         1         1         1   
785132  0.701403  3.440511 -0.015603  0.471097         0         0         0   

        Column13  Column15  Colu

In [ ]:
df_cleaned = t.dropna()

In [ ]:
df_cleaned = data.dropna()